#
# GEANT4 - G4simu pre_init macro
#
# A.P. Colijn 08-03-2012

# physics list to select
/run/physics/setEMlowEnergyModel emlivermore
# /run/physics/setEMlowEnergyModel empenelope
# /run/physics/setHadronicModel    G4QGSP_BERT_HP
/run/physics/setHadronicModel    G4QGSP_BERT
/run/physics/setCerenkov         false

# do we like to have the physics histograms or not?
/run/physics/setHistograms true

# format of the output ntuple
/G4simu/analysis/setTreeType compact
